"""
Filled-document export to .docx (FR-10).

Carries the professional-responsibility notice required by NG-1 / §13: every
export is explicitly a draft requiring attorney review.
"""
from __future__ import annotations

import io
from typing import List

from docx import Document
from docx.shared import Pt, RGBColor

from .models import FilledField

REVIEW_NOTICE = (
    "DRAFT — ATTORNEY REVIEW REQUIRED. Generated by Verbatim from the matter's "
    "case file. Fields marked NEEDS REVIEW were not grounded in the source and "
    "must be completed by a licensed attorney, who remains responsible for the "
    "final document."
)


def export_docx(title: str, filled_text: str, fields: List[FilledField]) -> bytes:
    doc = Document()

    notice = doc.add_paragraph()
    run = notice.add_run(REVIEW_NOTICE)
    run.italic = True
    run.font.size = Pt(8)
    run.font.color.rgb = RGBColor(0x8A, 0x6D, 0x00)

    doc.add_heading(title or "Filled Document", level=1)

    for block in filled_text.split("\n"):
        doc.add_paragraph(block)

    # Provenance appendix (auditability, NFR-6)
    doc.add_page_break()
    doc.add_heading("Provenance & Review Appendix", level=2)
    for f in fields:
        p = doc.add_paragraph()
        p.add_run(f"{f.label}: ").bold = True
        if f.found:
            p.add_run(f.value)
            src = doc.add_paragraph()
            cite = f.source_document or "unknown"
            if f.source_page:
                cite += f", p. {f.source_page}"
            q = src.add_run(
                f'    source: "{f.source_quote or ""}" — {cite}'
            )
            q.italic = True
            q.font.size = Pt(8)
        else:
            warn = p.add_run("NEEDS REVIEW (not grounded in case file)")
            warn.bold = True
            warn.font.color.rgb = RGBColor(0xB0, 0x00, 0x00)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
